config setup
    uniqueids=never
    charondebug="ike 2, knl 2, cfg 2, net 2, esp 2, dmn 2, mgr 2"

conn %default
    keyexchange=ikev1
    authby=secret
    ike=aes256-sha1-modp1024
    esp=aes256-sha1
    keyingtries=0
    ikelifetime=24h
    keylife=8h
    dpdaction=clear
    dpddelay=30s
    dpdtimeout=120s

conn L2TP-PSK
    keyexchange=ikev1
    left=%any
    leftid=@%any
    leftsubnet=0.0.0.0/0
    leftfirewall=yes
    right=%any
    rightprotoport=17/1701
    auto=add
